### ISSUE TITLE
How can I use it with custom images?

### ISSUE THREAD

**Issue by atzoriandrea** [fkluger/Vanishing_Points_GCPR17#2]
I want to use the framework with my images, but I don't understand how to do it. Thanks in advance.

**Comment by hashimK** [comment]
Yes, how to use it on any random image? example.py needs a .pkl file for test image. How to generae .pkl file for any random image to test?

**Comment by fkluger** [comment]
The example.py processes all images located in the assets/examples folder by default. It uses the create_data_pickles function from evaluation.py.
If you just want to try the algorithm on another image, you can simply put the image file in the assets/examples folder. If you want to integrate it into your own framework, you'll probably have to modify the code yourself.

**Comment by hashimK** [comment]
Thanks! It works that way :)
