### ISSUE TITLE
Output vanishing points

### ISSUE THREAD

**Issue by Brakebein** [fkluger/Vanishing_Points_GCPR17#7]
Thanks for sharing your code.

I'm trying to estimate the intrinsic camera parameters from the vanishing points. For that, I need to output the vanishing points (in image coordinates). However, I'm not sure where in the code the final vanishing points are computed (in which coordinate system), so I could output them.

Can you please point me to respective section in code or give me any other hint?

**Comment by fkluger** [comment]
Have a look at the [calculate_horizon_and_ortho_vp](https://github.com/fkluger/vanishing_points_2017/blob/62f7ee59933d5b1ab197da21e45b67c78c72ac87/calc_horizon.py#L19) function, which is also used in the [example.py](https://github.com/fkluger/vanishing_points_2017/blob/62f7ee59933d5b1ab197da21e45b67c78c72ac87/example.py#L65) script.
It returns a tuple `(hP1, hP2, zVP, hVP1, hVP2, best_combo)`:
- `hP1` and `hP2` are the two points which define the horizon line
- `zVP`, `hVP1` and `hVP2` are the three vanishing points which are estimated to correspond to orthogonal vanishing directions, i.e. the ones you need for camera parameter estimation.
- `best_combo` just contains the indices of the three orthogonal VPs in the array of all detected VPs (probably not relevant for you).

The vanishing points are given in normalised homogeneous coordinates (as a 3d vector). You get normalised and centred image coordinates by dividing by the third coordinate, e.g.:
```
zVP = zVP / zVP[2]
```

They then have to be rescaled to original image coordinates:
```
scale = 640. / np.maximum(width, height)
width *= scale
height *= scale
zVP[0] = zVP[0] * 640 / 2.0 + width / 2.0
zVP[1] = -zVP[1] * 640 / 2.0 + height / 2.0
```
(Assuming input images are rescaled to 640px as in example.py)

Hope this helps!

**Comment by Brakebein** [comment]
Thank you very much! That really helped me a lot.
